# Generated by Django 5.0.7 on 2024-07-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0004_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
