# Generated by Django 5.0.7 on 2024-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0020_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
