# Generated by Django 5.0.7 on 2024-07-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0021_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
