# Generated by Django 5.0.7 on 2024-07-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0022_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
