# Generated by Django 5.0.7 on 2024-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0024_alter_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10, null=True),
        ),
    ]
