# Generated by Django 5.0.7 on 2024-08-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0027_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_images/default-profile-pic.png', null=True, upload_to='profile_images/'),
        ),
    ]
