# Generated by Django 5.1.1 on 2024-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0041_notification_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurring_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurring_interval',
            field=models.CharField(blank=True, choices=[('minute', 'Every Minute'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
    ]
