# Generated by Django 5.1.1 on 2024-09-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0042_task_recurring_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurring_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
