# Generated by Django 5.1.1 on 2024-09-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0046_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
