# Generated by Django 5.0.7 on 2024-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0010_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reccuring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_interval',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
    ]
