# Generated by Django 5.0.7 on 2024-07-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0023_alter_profile_profile_pic_alter_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
