# Generated by Django 5.0.7 on 2024-07-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0025_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-profile-pic.png', null=True, upload_to='static/img/'),
        ),
    ]
