# Generated by Django 5.0.7 on 2024-08-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0028_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
