# Generated by Django 5.1 on 2024-08-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0033_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
